apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: demo-voting-app

spec:
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: demo-voting-app

    spec:
      containers:
        - name: voting-containers
          image: docker/example-voting-app-vote
          ports:
            - containerPort: 80

  replicas: 1
  selector:
     name: voting-pod
     app: demo-voting-app     