apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: demo-voting-app

spec:
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: demo-voting-app

    spec:
      containers:
        - name: worker-containers
          image: docker/example-voting-app-worker
          
  replicas: 1
  selector:
     name: worker-pod
     app: demo-voting-app     